schema_version: 1

context:
  name: asciiquarium
  version: 1.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://robobunny.com/projects/${{ name }}/${{ name }}_${{ version }}.tar.gz
  sha256: dc804ceade4e0aa6c881cdecc601f5b35540662f9c51c585e5a231408db766b2

build:
  number: 1
  noarch: generic
  script: mkdir -p $PREFIX/bin && cp asciiquarium $PREFIX/bin/ && chmod +x $PREFIX/bin/asciiquarium

requirements:
  run:
    - __unix
    - perl

tests:
  - script:
      - test -f $PREFIX/bin/asciiquarium

about:
  summary: Enjoy the mysteries of the sea from the safety of your own terminal!
  license: GPL-2.0-only
  license_file: gpl.txt
  homepage: https://robobunny.com/projects/asciiquarium/html/

extra:
  recipe-maintainers:
    - pavelzw
